config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/webhooks/stripe'
  devise_for :users
  resource :subscription
  resources :products
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :charges

  def stripe_customer
    if stripe_id
      Stripe::Customer.retrieve(stripe_id)
    else 
      stripe_customer = Stripe::Customer.create(email: email)
      update(stripe_id: stripe_customer.id)
      stripe_customer
    end
  end 

  def subscribed?
    stripe_subscription_id? || (expires_at? && Time.zone.now < expires_at)
  end
end

app/models/webhooks/charge_succeeded.rb
module Webhooks
  class ChargeSucceeded
   def call(event)
     charge = event.data.object

     user = User.find_by(stripe_id: charge.customer)

     c = user.charges.where(stripe_id: charge.id).first_or_create
     c.update(
       amount: charge.amount,
       card_brand: charge.source.brand,
       card_last4: charge.source.last4,
       card_exp_month: charge.source.exp_month,
       card_exp_year: charge.source.exp_year
     )
   end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :secret)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    customer = current_user.stripe_customer

    begin
      subscription = customer.subscriptions.create(
        source: params[:stripeToken],
        plan: params[:plan],
      )

      current_user.assign_attributes(stripe_subscription_id: subscription.id, expires_at: nil)
      current_user.assign_attributes(
        card_brand: params[:card_brand],
        card_last4: params[:card_last4],
        card_exp_month: params[:card_exp_month],
        card_exp_year: params[:card_exp_year]
      ) if params[:card_last4]

      current_user.save

      flash.notice = "Thanks for subscribing!"
      redirect_to root_path
    rescue Stripe::CardError => e 
      flash.alert = e.message
      render action: :new
    end
   end

   def show
   end

   def update
    customer = current_user.stripe_customer
    begin
     source = customer.sources.create(source: params[:stripeToken])
     customer.default_source = source.id
     customer.save
     current_user.assign_attributes(
      card_brand: params[:card_brand],
      card_last4: params[:card_last4],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year]
    )
     current_user.save

     flash.notice = "Your card was updated successfully"
     redirect_to root_path
    
    rescue Stripe::CardError => e
     flash.alert = e.message
     render action: :show
    
    end
   end

   def destroy
    customer = current_user.stripe_customer
    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    expires_at = Time.zone.at(subscription.current_period_end)
    current_user.update(expires_at: expires_at, stripe_subscription_id: nil)
    redirect_to root_path, notice: "You have cancelled your subscription. Yo will have access until #{current_user.expires_at.to_date}"
   end

  end  

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    case key
    when "notice" then "alert alert-info"
    when "alert" then "alert alert-danger"
    end 
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/',  'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
     <%= tag :meta, name: "stripe-public-key", content: Rails.application.credentials.production[:stripe_publishable_key] %>
    <% else %>
    <%= tag :meta, name: "stripe-public-key", content: Rails.application.credentials.development[:stripe_publishable_key] %>
    <% end %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Store</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Products", products_path, class: "nav-link" %>
          </li>
         
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item">
           <%= link_to "Account", edit_user_registration_path, class: "nav-link" %>
           </li>
           <li class="nav-item">
           <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
           </li>
          <% else %>
          <li class="nav-item">
           <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "Login", new_user_session_path, class: "nav-link" %>
           </li>
          <% end %>
           
        </ul>
      </div>
    </nav>
    <div class="container">
     <% flash.each do |key, value| %>
     <div class="<%= flash_class(key) %>">
      <%= value %>
     </div>
     <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :secret %>
    <%= form.text_area :secret %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.secret %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<% if user_signed_in? && current_user.subscribed? %>
<p>
  <strong>Secret:</strong>
  <%= @product.secret %>
</p>
<% else %>
<%= link_to "Subscribe", new_subscription_path(plan: "monthly"), class: "btn btn-primary" %>
<%= link_to "Subscribe", new_subscription_path(plan: "yearly"), class: "btn btn-primary" %>
<% end %>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/subscriptions/new.html.erb
<h1>Subscribe</h1>

<% if current_user.card_last4? %>
  <%= form_with url: subscription_path, id: "existing-card" do |form| %>
    <p>Pay with existing card</p> 
    <div><strong>Card on file:</strong> <%= current_user.card_brand %> (**** **** **** <%= current_user.card_last4 %>)</div>
    <div><strong>Expiration:</strong> <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>
    <p>or <%= link_to "Add a new card", "#", class: "show-card-form" %></p><!-- No link, handled by javascript -->
    
    <%= hidden_field_tag :plan, params[:plan] %>
    <button class="btn btn-primary">Submit Payment</button>
 <% end %>
<% end %>

<%= form_with url: subscription_path, id: "payment-form", class: (current_user.card_last4? ? "none" : nil) do |form| %>
  <div class="form-row mt-4">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element" class="form-control">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <%= hidden_field_tag :plan, params[:plan] %>

  <button class="btn btn-primary">Submit Payment</button>


<% end %>

app/views/subscriptions/show.html.erb
<h1>Update your card</h1>
<%= form_with url: subscription_path, method: :put, id: "payment-form" do |form| %>
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element" class="form-control">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button>Submit Payment</button>
</form>
<% end %>